[notification]
background_opacity = 0.7
enable_daemon = true
layer = "layer"
position = "top_center"
offset_y = 25

[notification.filter.niri]
enabled = true
match = "niri"
show_toast = true
save_history = false
play_sound = false
