[shell]
clipboard_auto_paste = "off"
clipboard_enabled = false
font_family = "JetBrains Mono Nerd Font"
lang = "en"
offline_mode = false
password_style = "random"
polkit_agent = true
settings_show_advanced = false
show_location = true
telemetry_enabled = false
ui_scale = 1.1
avatar_path = "~/.face"

[shell.animation]
enabled = true
speed = 2

[shell.shadow]
alpha = 0.55000000000000004
blur = 12
offset_x = 2
offset_y = 2

[shell.panel]
transparency_mode = "glass"
borders = true
shadow = true
session_placement = "floating"
session_position = "center"
open_near_click_control_center = true

[shell.mpris]
blacklist = ["zen", "zen-twilight"]

[[shell.session.actions]]
action = "logout"
shortcut = "1"

[[shell.session.actions]]
action = "lock_and_suspend"
label = "Suspend"
shortcut = "2"

[[shell.session.actions]]
action = "reboot"
shortcut = "3"

[[shell.session.actions]]
action = "shutdown"
shortcut = "4"
variant = "destructive"
