# Theming
font: JetBrainsMono Nerd Font 12
separator: " ➜ "
border_width: 2
corner_r: 20
padding: 15 # Defaults to corner_r
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 8
margin_bottom: 8
margin_left: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: false

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
  - key: "a"
    desc: Apps
    submenu:
      - key: "k"
        desc: Terminal (Kitty + tmux)
        cmd: kitty -e tmux new-session -A -s "kitty"
      - key: "K"
        desc: Terminal (Kitty)
        cmd: kitty
      - key: "b"
        desc: Browser (Zen)
        cmd: ~/.local/bin/focus-or-spawn zen-twilight ~/Downloads/zen/zen
      - key: "B"
        desc: Browser (Zen - Private Window)
        cmd: ~/.local/bin/zen --private-window
      - key: "e"
        desc: Files (Nautilus)
        cmd: nautilus
      - key: "y"
        desc: Files (Yazi)
        cmd: ~/.local/bin/yazi-window
      - key: "n"
        desc: Neovim
        cmd: gtk-launch neovim
      - key: "i"
        desc: IntelliJ IDEA
        cmd: ~/.local/share/JetBrains/Toolbox/apps/intellij-idea/bin/idea -Dawt.toolkit.name=WLToolkit
      - key: "c"
        desc: VS Code
        cmd: code --enable-features=UseOzonePlatform --ozone-platform=wayland
      - key: "p"
        desc: Neovim edit popup
        cmd: ~/.local/bin/nvim-edit-popup
      - key: "m"
        desc: Music (Deezer)
        cmd: ~/.local/bin/focus-or-spawn "dev.aunetx.deezer" "flatpak run dev.aunetx.deezer"
      - key: "r"
        desc: Resources
        cmd: flatpak run net.nokyan.Resources

  - key: "u"
    desc: UI
    submenu:
      - key: "c"
        desc: Control center
        cmd: noctalia msg panel-toggle control-center
      - key: "b"
        desc: Toggle bar
        cmd: noctalia msg bar-toggle
      - key: "N"
        desc: Clear notifications
        cmd: noctalia msg notification-clear-history
      # - key: "w"
      #   desc: Weekly calendar
      #   cmd: noctalia msg plugin:weekly-calendar togglePanel
      - key: ","
        desc: Settings
        cmd: noctalia msg settings-toggle

  - key: "v"
    desc: Vicinae
    submenu:
      - key: "v"
        desc: Launcher
        cmd: vicinae toggle
      - key: "c"
        desc: Clipboard history
        cmd: vicinae vicinae://launch/clipboard/history
      - key: "w"
        desc: Switch windows
        cmd: vicinae vicinae://launch/wm/switch-windows
      - key: "e"
        desc: Emoji search
        cmd: vicinae vicinae://launch/core/search-emojis

  - key: "s"
    desc: System
    submenu:
      - key: "a"
        desc: Audio
        submenu:
          - key: "m"
            desc: Mute output
            cmd: wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
          - key: "M"
            desc: Mute input
            cmd: wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

      - key: "c"
        desc: Capture
        submenu:
          - key: "r"
            desc: Toggle screen recorder
            cmd: noctalia msg plugin noctalia/screen_recorder:service all start
          - key: "f"
            desc: Screenshot (full screen)
            cmd: niri msg action screenshot-screen
          - key: "s"
            desc: Screenshot (area, no pointer)
            cmd: niri msg action screenshot --show-pointer=false
          - key: "w"
            desc: Screenshot (window)
            cmd: niri msg action screenshot-window
          - key: "t"
            desc: Screnshot (OCR, Google Lens)
            cmd: qs -c QuickSnip -n

      - key: "n"
        desc: Network
        submenu:
          - key: "w"
            desc: Wi-Fi toggle
            cmd: noctalia msg wifi-toggle
          - key: "b"
            desc: Bluetooth toggle
            cmd: noctalia msg bluetooth-toggle

      - key: "d"
        desc: Toggle DND
        cmd: noctalia msg notification-dnd-toggle
      - key: "f"
        desc: Freeze window
        cmd: ~/.local/opt/wl-freeze/wl-freeze -a
      - key: "i"
        desc: Toggle auto suspend (idle inhibitor)
        cmd: noctalia msg caffeine-toggle
      - key: "l"
        desc: Lock screen
        cmd: noctalia msg session lock
      - key: "m"
        desc: Toggle Dark/Light mode
        cmd: niri msg action do-screen-transition --delay-ms=500; ~/.local/bin/toggle-dark-mode
      - key: "s"
        desc: Change color scheme
        cmd: ~/.local/bin/vicinae-colorscheme-selector
      - key: "w"
        desc: Change wallpaper
        cmd: ~/.local/bin/vicinae-wallpaper-selector

  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Suspend
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: systemctl reboot
      - key: "p"
        desc: Power off
        cmd: systemctl poweroff
      - key: "m"
        desc: Power off monitors
        cmd: niri msg action power-off-monitors

  - key: "w"
    desc: Window
    submenu:
      - key: "l"
        desc: Layout
        submenu:
          - key: "o"
            desc: Overview
            cmd: niri msg action toggle-overview
          - key: "c"
            desc: Close window
            cmd: niri msg action close-window
          - key: "t"
            desc: Toggle tabbed columns
            cmd: niri msg action toggle-column-tabbed-display
          - key: "f"
            desc: Toggle floating
            cmd: niri msg action toggle-window-floating
          - key: "F"
            desc: Switch focus floating/tiling
            cmd: niri msg action switch-focus-between-floating-and-tiling
          - key: "["
            desc: Consume/expel left
            cmd: niri msg action consume-or-expel-window-left
          - key: "]"
            desc: Consume/expel right
            cmd: niri msg action consume-or-expel-window-right

      - key: "r"
        desc: Resize
        submenu:
          - key: "p"
            desc: Next column width preset
            cmd: niri msg action switch-preset-column-width
            keep_open: true
          - key: "P"
            desc: Next window height preset
            cmd: niri msg action switch-preset-window-height
          - key: "0"
            desc: Reset window height
            cmd: niri msg action reset-window-height
          - key: "-"
            desc: Column width -10%
            cmd: niri msg action set-column-width -- "-10%"
          - key: "="
            desc: Column width +10%
            cmd: niri msg action set-column-width -- "+10%"
          - key: "_"
            desc: Window height -10%
            cmd: niri msg action set-window-height -- "-10%"
          - key: "+"
            desc: Window height +10%
            cmd: niri msg action set-window-height -- "+10%"

      - key: "m"
        desc: Maximize
        submenu:
          - key: "c"
            desc: Maximize column
            cmd: niri msg action maximize-column
          - key: "e"
            desc: Maximize window to edges
            cmd: niri msg action maximize-window-to-edges
          - key: "f"
            desc: Fullscreen window
            cmd: niri msg action fullscreen-window
          - key: "x"
            desc: Expand column to available width
            cmd: niri msg action expand-column-to-available-width

      - key: "v"
        desc: View
        submenu:
          - key: "c"
            desc: Center column
            cmd: niri msg action center-column
          - key: "C"
            desc: Center visible columns
            cmd: niri msg action center-visible-columns

      - key: "s"
        desc: Sidebar
        submenu:
          - key: "t"
            desc: Toggle window in sidebar
            cmd: ~/.local/bin/niri-sidebar-wrapper toggle-window
          - key: "v"
            desc: Toggle sidebar visibility
            cmd: ~/.local/bin/niri-sidebar-wrapper toggle-visibility
          - key: "f"
            desc: Flip sidebar order
            cmd: ~/.local/bin/niri-sidebar-wrapper flip
          - key: "r"
            desc: Reorder sidebar
            cmd: ~/.local/bin/niri-sidebar-wrapper reorder
          - key: "o"
            desc: Focus sidebar
            cmd: ~/.local/bin/niri-sidebar-wrapper focus

