promptToReturnFromSubprocess: false
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers
os:
  editPreset: 'nvim'
customCommands:
  - key: "G"
    command: "gh browse"
    context: "global"
    description: "Show github repo in browser"
