#!/usr/bin/env zsh

ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
ZVM_VI_EDITOR=${EDITOR:-nvim}
ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
ZVM_SYSTEM_CLIPBOARD_ENABLED=true
