# Catppuccin Mocha Palette

# Core
$base = rgb(1e1e2e)
$baseAlpha = 1e1e2e

$surface0 = rgb(313244)
$surface0Alpha = 313244

$surface1 = rgb(45475a)
$surface1Alpha = 45475a

$surface2 = rgb(585b70)
$surface2Alpha = 585b70

$overlay0 = rgb(6c7086)
$overlay0Alpha = 6c7086

$overlay1 = rgb(7f849c)
$overlay1Alpha = 7f849c

$overlay2 = rgb(9399b2)
$overlay2Alpha = 9399b2

$mantle = rgb(181825)
$mantleAlpha = 181825

$crust = rgb(11111b)
$crustAlpha = 11111b

# Text
$text = rgb(cdd6f4)
$textAlpha = cdd6f4

$subtext0 = rgb(a6adc8)
$subtext0Alpha = a6adc8

$subtext1 = rgb(bac2de)
$subtext1Alpha = bac2de

# Accents
$accent = rgb(cba6f7) # Mauve
$accentAlpha = cba6f7

$red = rgb(f38ba8)
$redAlpha = f38ba8

$green = rgb(a6e3a1)
$greenAlpha = a6e3a1

$yellow = rgb(f9e2af)
$yellowAlpha = f9e2af

$blue = rgb(89b4fa)
$blueAlpha = 89b4fa

$magenta = rgb(f5c2e7) # Pink
$magentaAlpha = f5c2e7

$cyan = rgb(89dceb) # Sky
$cyanAlpha = 89dceb

$orange = rgb(fab387) # Peach
$orangeAlpha = fab387
