# Catppuccin Latte Palette

# Core
$base = rgb(eff1f5)
$baseAlpha = eff1f5

$surface0 = rgb(ccd0da)
$surface0Alpha = ccd0da

$surface1 = rgb(bcc0cc)
$surface1Alpha = bcc0cc

$surface2 = rgb(acb0be)
$surface2Alpha = acb0be

$overlay0 = rgb(9ca0b0)
$overlay0Alpha = 9ca0b0

$overlay1 = rgb(8c8fa1)
$overlay1Alpha = 8c8fa1

$overlay2 = rgb(7c7f93)
$overlay2Alpha = 7c7f93

$mantle = rgb(e6e9ef)
$mantleAlpha = e6e9ef

$crust = rgb(dce0e8)
$crustAlpha = dce0e8

# Text
$text = rgb(4c4f69)
$textAlpha = 4c4f69

$subtext0 = rgb(6c6f85)
$subtext0Alpha = 6c6f85

$subtext1 = rgb(5c5f77)
$subtext1Alpha = 5c5f77

# Accents
$accent = rgb(8839ef) # Mauve
$accentAlpha = 8839ef

$red = rgb(d20f39)
$redAlpha = d20f39

$green = rgb(40a02b)
$greenAlpha = 40a02b

$yellow = rgb(df8e1d)
$yellowAlpha = df8e1d

$blue = rgb(1e66f5)
$blueAlpha = 1e66f5

$magenta = rgb(ea76cb) # Pink
$magentaAlpha = ea76cb

$cyan = rgb(04a5e5) # Sky
$cyanAlpha = 04a5e5

$orange = rgb(fe640b) # Peach
$orangeAlpha = fe640b
