promptToReturnFromSubprocess: false
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers
  branchLogCmd: git log --graph --color=always --pretty=format:"%C(magenta)%h %C(white) %an  %ah%C(auto)  %D%n%s%n" {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --pretty=format:"%C(magenta)%h %C(white) %an  %ah%C(auto)  %D%n%s%n"
os:
  editPreset: 'nvim'
customCommands:
  - key: "G"
    command: "gh browse --branch $(git rev-parse --abbrev-ref HEAD)"
    context: "global"
    description: "Show github repo in browser"
keybinding:
  universal:
    scrollUpMain: <c-u>
    scrollDownMain: <c-d>
