#!/usr/bin/env bash
# @vicinae.schemaVersion 1
# @vicinae.title Sink Picker
# @vicinae.mode silent
# @vicinae.icon icons/sink.png

set -euo pipefail

selection=$(
  pactl list sinks |
    awk '
        /^[[:space:]]*Description:/ {
            sub(/^[[:space:]]*Description:[[:space:]]*/, "")
            print
        }
    ' |
    "$HOME"/.local/bin/dmenu-picker --no-quick-look -p "Choose audio sink"
)

[ -z "$selection" ] && exit 0

sink=$(
  pactl list sinks |
    awk -v desc="$selection" '
        /^[[:space:]]*Name:/ {
            sub(/^[[:space:]]*Name:[[:space:]]*/, "")
            name = $0
        }

        /^[[:space:]]*Description:/ {
            sub(/^[[:space:]]*Description:[[:space:]]*/, "")
            if ($0 == desc) {
                print name
                exit
            }
        }
    '
)

pactl set-default-sink "$sink"
