#!/usr/bin/env zsh

local PLUGIN_VERSION="1.0"
local CURRENT_CONFIG_VER="$(git config --global --get zsh.conv-commit.version 2>/dev/null)"
local -a _conv_types
_conv_types=(build chore ci docs feat fix perf refactor revert style test wip)

local SCRIPT_DIR="${0:A:h}"
local WORKER_PATH="$SCRIPT_DIR/git-conv-worker"
local ALIASES_FILE="$HOME/.config/git/conventional-commit-aliases.local"

_generate_completions() {
  local completions_dir="${ZDOTDIR}/completions"
  [[ ! -d "$completions_dir" ]] && mkdir -p "$completions_dir"

  local completion_template='#autoload

_arguments -s -S \
  '\''(-s --scope)'\''{-s,--scope}'\''[Add a scope]:scope:'\'' \
  '\''(-a --attention)'\''{-a,--attention}'\''[Mark as breaking change (adds !)]'\'' \
  '\''1:commit message:'\'' \
  '\''*:: :_git-commit'\''
'

  for type in "${_conv_types[@]}"; do
    local alias_name=$type
    [[ "$type" == "revert" ]] && alias_name="rev"

    echo "$completion_template" > "$completions_dir/_git-${alias_name}"
  done
}

_generate_git_aliases() {
  cat > "$ALIASES_FILE" << EOF
# Auto-generated git aliases for conventional commits
# Generated by conventional-commits.zsh v${PLUGIN_VERSION}
[alias]
EOF

  for type in "${_conv_types[@]}"; do
    local alias_name=$type
    [[ "$type" == "revert" ]] && alias_name="rev"

    echo "  ${alias_name} = !$WORKER_PATH $type" >> "$ALIASES_FILE"
  done

  local include_path="$(git config --global --get-all include.path | grep -F "$ALIASES_FILE")"
  if [[ -z "$include_path" ]]; then
    git config --global --add include.path "$ALIASES_FILE"
  fi
}

if [[ "$CURRENT_CONFIG_VER" != "$PLUGIN_VERSION" ]]; then
  _generate_git_aliases
  _generate_completions
  git config --global zsh.conv-commit.version "$PLUGIN_VERSION"
fi
