include themes/current-theme

font_family       JetBrainsMono Nerd Font
font_size         12.0
font_features     JetBrainsMonoNFM-Regular +liga +calt +dlig
disable_ligatures cursor
modify_font       cell_height 120%

hide_window_decorations  yes
window_padding_width     8

cursor                none
cursor_blink_interval 0

notify_on_cmd_finish unfocused
shell_integration    enabled

confirm_os_window_close 0
