console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  magenta = '#F265B8'
  red = '#F25754'
  purple = '#c19fed'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:grey'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    template = ' {{ .FormattedMs }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{if or (eq .Env.POSH_VI_MODE "command") (eq .Env.POSH_VI_MODE "visual")}}❮{{else}}❯{{end}}'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if eq .Env.POSH_VI_MODE "visual"}}p:purple{{end}}',
      '{{if gt .Code 0}}p:red{{end}}',
      '{{if eq .Code 0}}p:magenta{{end}}'
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
